Page({
  data:{
    dinosaur:[
      {
        dname:"霸王龙",
        imgsrc:"./dinosaur/lexus.jpg"
      },
      {
        dname:"迅猛龙",
        imgsrc:"./dinosaur/velociraptor.jpg"
      },
      {
        dname:"翼龙",
        imgsrc:"./dinosaur/pterosaur.jpg"
      },
      {
        dname:"腕龙",
        imgsrc:"./dinosaur/brachiosaurus.jpg"
      },
      {
        dname:"甲龙",
        imgsrc:"./dinosaur/ankylosaur.jpg"
      },
      {
        dname:"剑龙",
        imgsrc:"./dinosaur/jianlong.png"
      },
      {
        dname:"黑瑞龙",
        imgsrc:"./dinosaur/heiruilong.png"
      },
      {
        dname:"副栉龙",
        imgsrc:"./dinosaur/fuzhilong.png"
      },
    ]
  }
})